# Generated by Django 5.1.1 on 2025-05-04 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('licence_number', models.CharField(max_length=100)),
                ('licence_expiry_date', models.DateField()),
                ('driving_licence', models.ImageField(upload_to='driving_licences/')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_agent_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
