# Generated by Django 5.1.1 on 2025-05-29 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery_agent', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordervisibility',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.order'),
        ),
        migrations.AlterUniqueTogether(
            name='ordervisibility',
            unique_together={('order', 'agent')},
        ),
    ]
