# Generated by Django 5.1.1 on 2025-05-25 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_agent', '0001_initial'),
        ('products', '0014_remove_invoice_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderVisibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rejected', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery_agent.deliveryagent')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.order')),
            ],
            options={
                'unique_together': {('order', 'agent')},
            },
        ),
    ]
