# Generated by Django 5.1.1 on 2025-05-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_agent', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryagent',
            name='own_vehicle',
            field=models.BooleanField(default=False),
        ),
    ]
