# Generated by Django 5.2 on 2025-04-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_seller_user_alter_seller_business_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seller',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seller',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
