# Generated by Django 5.2 on 2025-04-20 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_seller_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='is_active',
        ),
    ]
