# Generated by Django 5.2 on 2025-04-22 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_remove_seller_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='email',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='full_name',
        ),
    ]
