# Generated by Django 5.1.1 on 2025-06-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('About to Deliver', 'About to Deliver'), ('Delivered', 'Delivered'), ('Rejected', 'Rejected')], default='placed', max_length=20),
        ),
    ]
