# Generated by Django 5.1.1 on 2025-05-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_orderitem_selected_color_orderitem_selected_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='selected_color',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='selected_size',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
