# Generated by Django 5.1.1 on 2025-05-25 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='pdf_file',
        ),
    ]
