# Generated by Django 5.1.1 on 2025-05-25 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_agent', '0002_ordervisibility'),
        ('products', '0014_remove_invoice_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='accept_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery_agent.deliveryagent'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
