# Generated by Django 5.1.1 on 2025-05-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_order_accept_status_order_assigned_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='accept_status',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('placed', 'Order Placed'), ('pending', 'Pending Delivery'), ('transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='placed', max_length=20),
        ),
    ]
