# Generated by Django 5.1.1 on 2025-05-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_order_accept_status_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='issue_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
